[project]
name = "binf200-bio-sequences-structures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bio>=1.8.0",
    "marimo[recommended]>=0.14.16",
    "seaborn>=0.13.2",
]
